version: '3.1'
services:
  stats-server:
    build: ./stats/server/
    image: stat-server
    container_name: stat-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic

  stats-db:
    image: postgres:13.7-alpine
    container_name: postgres-statistics-db
    ports:
      - "6541:5432"
    environment:
       POSTGRES_DB : statistic
       POSTGRES_NAME : postgres
       POSTGRES_PASSWORD : root