version: '3.1'
services:
  stats-server:
    build: ./stats/server/
    image: stat-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/statistic

  stats-db:
    image: postgres:14-alpine
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
       POSTGRES_DB : statistic
       POSTGRES_NAME : postgres
       POSTGRES_PASSWORD : root

  ewm-service:
   ports:
     - "8080:8080"
   build: ./main/
   image: main-service
   container_name: main_container
   depends_on:
     - ewm-db
     - stats-db
   environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm

  ewm-db:
    image: postgres:14-alpine
    container_name: main_db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB : ewm
      POSTGRES_USER : ewm_admin
      POSTGRES_PASSWORD : root